name: 'Terraform - Deploy'

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
          terraform_wrapper: false

      - name: Terraform apply
        id: init
        run: pwd && ls && terraform init && terraform apply -auto-approve
        env:
          TF_VAR_confluent_cloud_api_key: ${{ secrets.TF_VAR_confluent_cloud_api_key }}
          TF_VAR_confluent_cloud_api_secret: ${{ secrets.TF_VAR_confluent_cloud_api_secret }}
        shell: bash